name:  Build and Publish DocC

on:
  release:
    types: [published]

jobs:
  test:
    name: 'Build and Publish DocC'
    runs-on: macOS
    permissions:
      contents: write

    steps:
    - name: Check out Repository
      uses: actions/checkout@v2

    - name: Build DocC
      run: |
            set -o pipefail && xcodebuild docbuild \
                -scheme MockingStar \
                -skipMacroValidation \
                -derivedDataPath ./.Docc \
                -workspace ./MockingStar.xcworkspace | xcbeautify --renderer github-actions

    - name: Export DocC
      run: $(xcrun --find docc) process-archive transform-for-static-hosting ./.Docc/Build/Products/Debug/MockingStar.doccarchive --output-path ./.docsExport --hosting-base-path mockingstar

    - name: Push DocC
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: docc
        FOLDER: ./.docsExport
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        MESSAGE: "Build: ({sha}) {msg}"