name:  Release CLI

on:
  release:
    types: [published]

jobs:
  test:
    name: 'Release CLI App'
    runs-on: macOS
    permissions:
      contents: write

    steps:
    - name: Check out Repository
      uses: actions/checkout@v2

    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

    - name: Build Mocking Star CLI
      run: swift build -c release --package-path ./MockingStarExecutable      

    - name: Create Zip
      run: |
            mkdir .build || echo "build folder created"
            cp MockingStarExecutable/.build/release/MockingStar ./.build/MockingStar 
            cd ./.build/ && zip -r MockingStar-CLI.zip MockingStar

    - name: Create a Release
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ github.event.release.tag_name }}
        name: MockingStar - Release ${{ github.event.release.tag_name }}
        artifacts: '.build/MockingStar-CLI.zip'
        allowUpdates: true
        omitBodyDuringUpdate: true
        makeLatest: false