name:  Release App

on:
  push:
    tags:
      - "*"
  workflow_dispatch:
    inputs:
      version:
        description: 'Version Tag'     
        required: true
        default: '1.0.0-1'

jobs:
  test:
    name: 'Release MockingStar App'
    runs-on: macOS
    permissions:
      contents: write

    steps:
    - name: Check out Repository
      uses: actions/checkout@v2

    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

    - name: Build App 
      run: swift run --package-path ./fastlaneRunner fastlaneRunner lane releaseAppLane
      env:
        CERT: ${{ secrets.CERT }}
        PASS: ${{ secrets.PASS }}
        CODESIGNING_IDENTITY: ${{ secrets.CODESIGNING_IDENTITY }}
        PROFILE: ${{ secrets.PROFILE }}
        TEAM_ID: ${{ secrets.TEAM_ID }}
        ASC_KEY_ID: ${{ secrets.ASC_KEY_ID }}
        ASC_ISSUER_ID: ${{ secrets.ASC_ISSUER_ID }}
        ASC_KEY: ${{ secrets.ASC_KEY }}
        VERSION: ${{ env.RELEASE_VERSION }}

    - name: Create Zip
      run: cd ./.build/appBuildOutput && zip -r MockingStar-App.zip MockingStar.app

    - name: Create a Release
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ env.RELEASE_VERSION }}
        name: MockingStar - Release ${{ env.RELEASE_VERSION }}
        artifacts: '.build/appBuildOutput/MockingStar-App.zip'
        allowUpdates: true