name:  Release CLI

on:
  release:
    types: [published]

jobs:
  test:
    name: 'Release CLI App'
    runs-on: macOS
    permissions:
      contents: write

    steps:
    - name: Check out Repository
      uses: actions/checkout@v2

    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

    - name: Build CLI App 
      run: swift run --package-path ./fastlaneRunner fastlaneRunner lane releaseCLILane
      
    - name: Create Zip
      run: cd ./.build/release/ && zip -r MockingStar-CLI.zip MockingStar

    - name: Create a Release
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ github.event.release.tag_name }}
        name: MockingStar - Release ${{ env.RELEASE_VERSION }}
        artifacts: '.build/release/MockingStar-CLI.zip'
        allowUpdates: true