name:  Release Linux CLI

on:
  release:
    types: [published]

jobs:
  test:
    name: 'Release Linux CLI App'
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Check out Repository
      uses: actions/checkout@v2

    - uses: swift-actions/setup-swift@v2

    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

    - name: Prepare Dependencies
      run: |
            sudo apt update
            sudo NEEDRESTART_MODE=a apt-get install \
                  binutils \
                  git \
                  gnupg2 \
                  libc6-dev \
                  libcurl4-openssl-dev \
                  libedit2 \
                  libgcc-9-dev \
                  libpython3.8 \
                  libsqlite3-0 \
                  libstdc++-9-dev \
                  libxml2-dev \
                  libz3-dev \
                  pkg-config \
                  tzdata \
                  unzip \
                  zlib1g-dev -y

    - name: Build Mocking Star CLI
      run: swift build -c release --package-path ./MockingStarExecutable --static-swift-stdlib

    - name: Create Zip
      run: |
            mkdir .build || echo "build folder created"
            cp MockingStarExecutable/.build/release/MockingStar ./.build/MockingStar
            cd ./.build/ && zip -r MockingStar-Linux-CLI.zip MockingStar

    - name: Create a Release
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ github.event.release.tag_name }}
        name: MockingStar - Release ${{ github.event.release.tag_name }}
        artifacts: '.build/MockingStar-Linux-CLI.zip'
        allowUpdates: true
        omitBodyDuringUpdate: true
        makeLatest: false