name:  Release Linux CLI

on:
  release:
    types: [published]

jobs:
  test:
    name: 'Release Linux CLI App'
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Check out Repository
      uses: actions/checkout@v2

    - uses: swift-actions/setup-swift@v2

    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

    - name: Build Mocking Star CLI
      run: swift build -c release --package-path ./MockingStarExecutable --static-swift-stdlib

    - name: Create Zip
      run: |
            mkdir .build || echo "build folder created"
            cp MockingStarExecutable/.build/release/MockingStar ./.build/MockingStar
            cd ./.build/ && zip -r MockingStar-Linux-CLI.zip MockingStar

    - name: Create a Release
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ github.event.release.tag_name }}
        name: MockingStar - Release ${{ env.RELEASE_VERSION }}
        artifacts: '.build/MockingStar-Linux-CLI.zip'
        allowUpdates: true
        omitBodyDuringUpdate: true