name:  Release App

on:
  push:
    tags:
      - "*"

jobs:
  test:
    name: 'Release MockingStar App'
    runs-on: macOS
    permissions:
      contents: write

    steps:
    - name: Check out Repository
      uses: actions/checkout@v2

    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

    - name: Build App 
      run: swift run --package-path ./fastlaneRunner fastlaneRunner lane releaseAppLane
      env:
        CERT: ${{ secrets.CERT }}
        CERT_PASS: ${{ secrets.CERT_PASS }}
        INSTALLER_CERT_NAME: ${{ secrets.INSTALLER_CERT_NAME }}
        KEYCHAIN_PASS: ${{ secrets.KEYCHAIN_PASS }}
        PROFILE: ${{ secrets.PROFILE }}
        TEAM_ID: ${{ secrets.TEAM_ID }}
        WWDR: ${{ secrets.WWDR }}
        AC_KEY_ID: ${{ secrets.AC_KEY_ID }}
        AC_ISSUER_ID: ${{ secrets.AC_ISSUER_ID }}
        AC_API_KEY: ${{ secrets.AC_API_KEY }}
        VERSION: ${{ env.RELEASE_VERSION }}